import os
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

EMAIL_ADDRESS  = ""
EMAIL_PASSWORD = ""
RECEIVER_EMAIL = ""
SMTP_HOST = "smtp.wp.pl" 
SMTP_PORT = 587

def _build_message(sender: str, receiver: str, attachment_path: str) -> MIMEMultipart:
    msg = MIMEMultipart()
    msg["From"]    = sender
    msg["To"]      = receiver
    msg["Subject"] = "Top Customers Report"

    body = (
        "Hi,\n\n"
        "Please find attached the automated Top Customers Report generated by our RPA pipeline.\n\n"
        "The report lists the 10 highest-value customers based on the latest transaction data.\n\n"
        "This email was sent automatically — please do not reply.\n\n"
        "Best regards,\n"
        "RPA Bot"
    )
    msg.attach(MIMEText(body, "plain"))

    filename = os.path.basename(attachment_path)
    with open(attachment_path, "rb") as f:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(f.read())

    encoders.encode_base64(part)
    part.add_header("Content-Disposition", f'attachment; filename="{filename}"')
    msg.attach(part)

    return msg



def send_report(attachment_path: str = "output.xlsx") -> None:

    if not os.path.exists(attachment_path):
        raise FileNotFoundError(
            f"[mailer] Attachment not found: {attachment_path}. "
            "Run processor.py first to generate the report."
        )

    print(f"[mailer] Preparing email for {RECEIVER_EMAIL} …")
    msg = _build_message(EMAIL_ADDRESS, RECEIVER_EMAIL, attachment_path)

    print(f"[mailer] Connecting to {SMTP_HOST}:{SMTP_PORT} …")
    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()         
        server.ehlo()
        server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        server.sendmail(EMAIL_ADDRESS, RECEIVER_EMAIL, msg.as_string())

    print("[mailer] ✓ Report sent successfully!")

if __name__ == "__main__":
    send_report(attachment_path="output.xlsx")
